verbose: false
instrumentation:
    root: .
    extensions:
        - .js
    default-excludes: true
    excludes: ['test/']
reporting:
    print: summary
    reports:
        - json
    dir: ./coverage
    watermarks:
        statements: [80, 95]
        lines: [80, 95]
        functions: [80, 95]
        branches: [80, 95]
