language: node_js
node_js:
  - '4'
  - '5'
  - '6'
script:
  - node --version
  - npm --version
  # linting
  - npm run lint
  # testing
  - npm run clean
  - npm run cover
  - npm run browser
  - npm run report
after_success:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
