language: node_js
os:
  - linux
  - osx
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4.2"
  - "stable"
before_build:
  - echo HERE
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then npm install -g nvm; fi
after_script:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
  - "cat coverage/lcov.info | ./node_modules/.bin/codacy-coverage"
