language: node_js
os:
  - linux
  - osx
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4.2"
  - "stable"
after_script:
  - "cat coverage/lcov.info | ./node_modules/.bin/coveralls"
  - "cat coverage/lcov.info | ./node_modules/.bin/codacy-coverage"
